<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html "http://www.w3.org/1999/xhtml">
<head>
<style>	
table {	    border-collapse: collapse; /* IE7 and lower */	    border-spacing: 0;	    width: 80%;    	    margin-left:auto;margin-right:auto;    }	
.mydata {	    font-family: 'trebuchet MS', 'Lucida sans', Arial;	    font-size: 10px;	   border: solid #ccc 1px;	    -moz-border-radius: 6px;	   -webkit-border-radius: 6px;	    border-radius: 6px;	    -webkit-box-shadow: 0 1px 1px #ccc; 	    -moz-box-shadow: 0 1px 1px #ccc; 	    box-shadow: 0 1px 1px #ccc;         }	
.mydata tr:hover {	    background: #fbf8e9;	    -o-transition: all 0.1s ease-in-out;	    -webkit-transition: all 0.1s ease-in-out;	    -moz-transition: all 0.1s ease-in-out;	    -ms-transition: all 0.1s ease-in-out;	    transition: all 0.1s ease-in-out;     }	
.mydata td, .mydata th {	    border-left: 1px solid #ccc;	    border-top: 1px solid #ccc;	    padding: 10px;	    text-align: left;    }	
.mydata th {	    background-color: #dce9f9;	    background-image: -webkit-gradient(linear, left top, left bottom, from(#ebf3fc), to(#dce9f9));	    background-image: -webkit-linear-gradient(top, #ebf3fc, #dce9f9);	    background-image:    -moz-linear-gradient(top, #ebf3fc, #dce9f9);	    background-image:     -ms-linear-gradient(top, #ebf3fc, #dce9f9);	    background-image:      -o-linear-gradient(top, #ebf3fc, #dce9f9);	    background-image:         linear-gradient(top, #ebf3fc, #dce9f9);	    -webkit-box-shadow: 0 1px 0 rgba(255,255,255,.8) inset; 	    -moz-box-shadow:0 1px 0 rgba(255,255,255,.8) inset;  	    box-shadow: 0 1px 0 rgba(255,255,255,.8) inset;        	    border-top: none; 	    text-shadow: 0 1px 0 rgba(255,255,255,.5); }	
.mydata td:first-child, 
.mydata th:first-child {	    border-left: none;}	
.mydata th:first-child {	    -moz-border-radius: 6px 0 0 0;	    -webkit-border-radius: 6px 0 0 0;	    border-radius: 6px 0 0 0; }	
.mydata th:last-child {	    -moz-border-radius: 0 6px 0 0;	    -webkit-border-radius: 0 6px 0 0;	    border-radius: 0 6px 0 0;}	
.mydata th:only-child{	   -moz-border-radius: 6px 6px 0 0;	    -webkit-border-radius: 6px 6px 0 0;	    border-radius: 6px 6px 0 0;}	
.mydata tr:last-child td:first-child {	    -moz-border-radius: 0 0 0 6px;	    -webkit-border-radius: 0 0 0 6px;	    border-radius: 0 0 0 6px;}	
.mydata tr:last-child td:last-child {	    -moz-border-radius: 0 0 6px 0;	    -webkit-border-radius: 0 0 6px 0;	    border-radius: 0 0 6px 0;}
</style></head>
 <body>
<table border=0><tr><td><img src="http://localhost/nh/assets/css/logoNH.gif" WIDTH=370></td></tr></table><table class="mydata" width="370"><tr><th COLSPAN=4>SLIP GAJI</th></tr><tr><tD colspan=2>NAMA</td><tD>:</td><tD>kary jakarta</td></tr><tr><tD colspan=2>JABATAN</td><tD>:</td><tD>Staff</td></tr><tr><tD colspan=2>GAJI BULAN</td><tD>:</td><tD>Maret 2014</td></tr></table ><table class="mydata" width="370"><tr><th COLSPAN=4>RINCIAN GAJI</th></tr><tr><td>1.</td><td>GAJI POKOK</td><td>:</td><td style="text-align:right">Rp. 1.450.000</td></tr><tr><td>2.</td><td>TUNJANGAN JABATAN</td><td>:</td><td style="text-align:right">Rp. 50.000</td></tr><tr><td>3.</td><td>TUNJANGAN FUNGSIONAL</td><td>:</td><td style="text-align:right">Rp. 75.000</td></tr><tr><td>4.</td><td>TUNJANGAN MASA KERJA</td><td>:</td><td style="text-align:right">Rp. 0</td></tr><tr><td>5.</td><td>UANG MAKAN</td><td>:</td><td style="text-align:right">Rp. 0</td></tr><tr><td>6.</td><td>TUNJANGAN TRANSPORT</td><td>:</td><td style="text-align:right">Rp. 0</td></tr><tr><td>7.</td><td>TUNJANGAN ANAK</td><td>:</td><td style="text-align:right">Rp. 495.000</td></tr><tr><td>&nbsp;</td><td COLSPAN=3><HR></td></tr><tr><td>&nbsp;</td><td>SUB TOTAL</td><td>:</td><td style="text-align:right">Rp. 2.070.000</td></tr><tr><td>8.</td><td>ANGSURAN PINJAMAN 1/20</td><td>:</td><td style="text-align:right">(Rp. 250.000)</td></tr><tr><td>9.</td><td>POTONGAN GAJI POKOK</td><td>:</td><td style="text-align:right">(Rp. 0)</td></tr><tr><td>&nbsp;</td><td COLSPAN=3><HR></td></tr><tr><th COLSPAN=3 >THP</th><th style="text-align:right">Rp. 1.820.000</th></tr><tr><td COLSPAN=4 >Masa Kerja :   00 Tahun, 07 Bulan, 22 Hari </td></tr><tr><td COLSPAN=4 >Akumulasi Keterlambatan : 0 Jam</td></tr><tr><td COLSPAN=4 >Tidak Hadir : 0 hari</td></tr></table></body>
</html>